version: '3.1'
services:
  api:
    image: side2022/dmc-api:latest
    build:
      context: ./
    volumes:
      - ./:/app/
    #environment:
    #  FLASK_APP: api.py
    #command: ["flask", "run", "-h", "0.0.0.0", "-p", "8080"]
    command: ["./start.sh"]
    ports:
      - 8080:8080
